In [62]:
import glob
import h5py
import matplotlib.pyplot as plt
import numpy as np
import os
import scipy

from neuropacks import NHP, PVC11
from sklearn.linear_model import LinearRegression

%matplotlib inline

# V1

In [11]:
base_path = os.path.join(os.environ['HOME'],
                         'data/pvc11/data/spikes_gratings')
monkey_paths = glob.glob(os.path.join(base_path, '*.mat'))

In [12]:
pvcs = [PVC11(data_path=monkey_path)
        for monkey_path in monkey_paths]

In [13]:
Xs = [pvc.get_design_matrix(form='cosine2')
      for pvc in pvcs]
Ys = [pvc.get_response_matrix(transform='square_root')
      for pvc in pvcs]

In [14]:
preferences_list = []

In [15]:
for pvc, X, Y in zip(pvcs, Xs, Ys):
    ols = LinearRegression()
    ols.fit(X, Y)
    _, preferences = pvc.get_tuning_modulation_and_preference(form='cosine2',
                                                              tuning_coefs=ols.coef_)
    preferences_list.append(preferences)

In [18]:
np.save('v1_preferences.npy', preferences)

# M1

In [19]:
base_path = os.path.join(os.environ['HOME'], 'data/nhp')
monkey_paths = glob.glob(os.path.join(base_path, '*.mat'))

In [20]:
nhps = [NHP(data_path=monkey_path)
        for monkey_path in monkey_paths]

In [29]:
positions = nhps[0].get_binned_positions(bin_width=0.15)
Y = nhps[0].get_response_matrix(bin_width=0.15)
x = positions[:, 0]
y = positions[:, 1]

In [48]:
angles = np.rad2deg(np.arctan2(np.ediff1d(y), np.ediff1d(x)))

In [64]:
Y.shape

(5867, 192)

In [40]:
np.rad2deg(np.arctan2(1, -1))

135.0

In [43]:
np.rad2deg(np.arctan2(1, -1))

135.0

In [56]:
woof.cursor_pos[0]

array([-114.40909985, -113.32296137, -112.23247527, ...,  -57.24131965,
        -57.24218896,  -57.24295368])

In [58]:
woof.cursor_pos[1]

array([66.18872713, 66.28512398, 66.38599637, ..., 58.95097488,
       58.95150602, 58.95201324])

In [63]:
angles = np.rad2deg(np.arctan2(np.ediff1d(nhps[0].cursor_pos[1]), np.ediff1d(nhps[0].cursor_pos[0])))

In [70]:
scipy.stats.binned_statistic(
    angles,
    angles,
    statistic='mean',
    bins=5867
)

BinnedStatisticResult(statistic=array([-179.96983896, -179.9073926 , -179.84736327, ...,  179.84406723,
        179.90700221,  179.96987307]), bin_edges=array([-179.99880226, -179.93744239, -179.87608252, ...,  179.87682314,
        179.93818301,  179.99954287]), binnumber=array([3017, 3020, 3024, ..., 5381, 5355, 5321]))

In [73]:
plt.plot(nhps[0].cursor_pos[0][:20], nhps[0].cursor_p)

array([ 5.07182009,  5.28494731,  5.54492172,  5.86053496,  6.2418526 ,
        6.70042137,  7.24898493,  7.90066732,  8.66793383,  9.56089449,
       10.58437722, 11.73430831, 12.99415699, 14.33196291, 15.69816265,
       17.02492641, 18.22878488, 19.21744655, 19.90110345, 20.2075514 ,
       20.09732737, 19.574703  , 18.68963141, 17.52682579, 16.18666349,
       14.76677943, 13.35079213, 12.00324384, 10.76659666,  9.66316888,
        8.70183676,  7.88266277,  7.19899454,  6.64031277,  6.19482108,
        5.85015235,  5.59335358,  5.41118968,  5.29026896,  5.2169991 ,
        5.17785109,  5.15983081,  5.15093977,  5.14054948,  5.11968087,
        5.0812216 ,  5.02006885,  4.93318227,  4.81951801,  4.67983724,
        4.51636028,  4.33205872,  4.12981113,  3.91214083,  3.68122789,
        3.43843657,  3.18388821,  2.91663681,  2.63509982,  2.33748605,
        2.0221616 ,  1.68779043,  1.33330692,  0.95799185,  0.56161788,
        0.14449051, -0.29255931, -0.74792361, -1.21873262, -1.70